### ISSUE TITLE
Dedi Drop

### ISSUE THREAD

**Issue by ThePowerfulOdin** [lkd70/LKD_ARK_AIO#1]
Starting up the dedi drop clicks on drop all instead of transfer all.

**Comment by lkd70** [comment]
Thanks, due to a recent change in the ark client the position of the buttons is incorrect. Fixing it now.

**Comment by lkd70** [comment]
Right, that's all fixed now: bbf22fe667126305d7742605f0f57b52b488b2ea
Auto updater should handle it on the next launch. Any other issues, please let me know.

**Comment by ThePowerfulOdin** [comment]
Thank you!
