### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by FatalWolff** [lkd70/LKD_ARK_AIO#2]
Hello, 
I've been looking at your raw data saved in the ARK_All_In_One.ahk and It doesnt seem to even Launch, there is Errors which prevents any new scripts I would like to add, or edit. I have been trying to teach myself how to use ahk but the code your using in yours seems to be errored or you are using a different ahk language.
Error: Call to nonexistent function
Specifically: Float(why.ResponseText
and line# 021-035
which makes it impossible to use and I can't modify or add scripts into the .exe executable.

**Comment by lkd70** [comment]
Please ensure you're using AutoHotKey v2. This script is not compatible with v1.

**Comment by FatalWolff** [comment]
Oh okay! Thanks for letting me know I messed around alot by myself with ahk
for 8 hours ad taught myself a new trick, also if you are interested I have
a really fast dedi drop ahk, bloodpack, seed maker, and feeding Dino's 100%
success rate even in 255 ping aslong as you are looking at them, I'm just
heading to bed now but if you send me your discord I could show you them
maybe you can incorporate them into your scripts

**Comment by lkd70** [comment]
Sure, I don't actively play at the moment but I will gladly implement them LKD70#7070 On discord.
